### ISSUE TITLE
The CoinBlockerLists are dead

### ISSUE THREAD

**Issue by ZeroDot1** [dead-hosts/CoinBlockersLists-hosts_git_ZeroDot1#1]
Hi @funilrys and all, 

Unfortunately my computer is completely broken this morning see the video.
https://drive.google.com/file/d/11xXSQ57f3PvD_41v71v5qp3iNX9o5_7b/view?usp=sharing 
It is now absolutely impossible to provide updates and support, the project and everything related to it is dead.
I am not able to buy a new computer.

Thanks to all supporters, it was a nice time.

Best regards ZeroDot1

**Comment by funilrys** [comment]
Sorry to read that ...
People are still fetching it from here. I'll keep it around for a few more months. 

Cheers!

**Comment by ZeroDot1** [comment]
Hi @funilrys, 
There is good news, I can continue the project after all, it was not easy to find good solutions, but it still worked.

The updates are secured.

I close here because the problem is solved and updates will be available again.
